universe = docker  
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel  
executable = run.sh 
transfer_input_files = worker.py, pub.pt, priv.pt, model.pt,  ref_models, submission.csv, run.sh
transfer_output_files =  submission.csv, ref_models
output = runlogs/mia.$(ClusterId).$(ProcId).out 
error = runlogs/mia.$(ClusterId).$(ProcId).err  
log = runlogs/mia.$(ClusterId).log  
should_transfer_files = YES  
request_GPUs = 1  
request_CPUs = 1 
request_memory = 4G  
requirements = UidDomain == "cs.uni-saarland.de"  
+WantGPUHomeMounted = true  
+WantScratchMounted = true  
queue 1